# Generated by Django 5.0.14 on 2026-05-09 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PROVISIONING', 'Provisioning'), ('PROVISIONED', 'Provisioned'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('justification', models.TextField(help_text='Reason for requesting privileged access')),
                ('requested_duration_minutes', models.PositiveIntegerField(default=60, help_text='Requested duration in minutes')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('deprovisioned_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference_id', models.CharField(blank=True, help_text='Provider-specific reference ID (e.g., AWS assignment ID)', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='roles.privilegedrole')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='access_requests.accessrequest')),
            ],
            options={
                'ordering': ['decided_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['status'], name='access_requ_status_ec5153_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['requester', 'status'], name='access_requ_request_adcdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['expires_at'], name='access_requ_expires_d343bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('request', 'approver')},
        ),
    ]
