# Generated by Django 5.0.14 on 2026-05-09 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, default='', help_text='Your Entra ID tenant ID (GUID from Azure portal)', max_length=128, verbose_name='Tenant ID (Directory ID)')),
                ('client_id', models.CharField(blank=True, default='', help_text='The Application (client) ID from your App Registration', max_length=128, verbose_name='Client ID (Application ID)')),
                ('client_secret', models.CharField(blank=True, default='', help_text='The client secret value from Certificates & Secrets', max_length=512, verbose_name='Client Secret')),
                ('redirect_uri', models.CharField(blank=True, default='', help_text='The redirect URI registered in the app (e.g. http://localhost:8080/accounts/callback/)', max_length=256, verbose_name='Redirect URI')),
                ('configured_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Configured by')),
            ],
            options={
                'verbose_name': 'Entra ID Configuration',
                'verbose_name_plural': 'Entra ID Configuration',
            },
        ),
    ]
