# Generated by Django 5.2.14 on 2026-05-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_entraconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='entraconfig',
            name='pim_auth_method',
            field=models.CharField(blank=True, default='', editable=False, help_text='Auto-detected: managed_identity, certificate, or client_secret', max_length=32, verbose_name='PIM Auth Method'),
        ),
        migrations.AddField(
            model_name='entraconfig',
            name='pim_client_id',
            field=models.CharField(blank=True, default='', help_text='Separate App Registration for PIM role management. Leave blank to reuse OIDC app.', max_length=128, verbose_name='PIM Client ID (optional)'),
        ),
        migrations.AddField(
            model_name='entraconfig',
            name='pim_client_secret',
            field=models.CharField(blank=True, default='', help_text='Client secret for the PIM management app (encrypted at rest). For production, use a certificate instead.', max_length=512, verbose_name='PIM Client Secret (optional)'),
        ),
        migrations.AddField(
            model_name='entraconfig',
            name='pim_tenant_id',
            field=models.CharField(blank=True, default='', help_text='Leave blank to use the same tenant as OIDC. Set if PIM app is in a different tenant.', max_length=128, verbose_name='PIM Tenant ID (optional)'),
        ),
        migrations.AlterField(
            model_name='entraconfig',
            name='client_id',
            field=models.CharField(blank=True, default='', help_text='The Application (client) ID from your OIDC login App Registration', max_length=128, verbose_name='OIDC Client ID (Application ID)'),
        ),
        migrations.AlterField(
            model_name='entraconfig',
            name='client_secret',
            field=models.CharField(blank=True, default='', help_text='The client secret for the OIDC login app (encrypted at rest)', max_length=512, verbose_name='OIDC Client Secret'),
        ),
        migrations.AlterField(
            model_name='entraconfig',
            name='redirect_uri',
            field=models.CharField(blank=True, default='', help_text='The redirect URI registered in the OIDC app (e.g. http://localhost:8080/accounts/callback/)', max_length=256, verbose_name='Redirect URI'),
        ),
    ]
