# Generated by Django 5.2.14 on 2026-06-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_entraconfig_pim_auth_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sso_instance_arn', models.CharField(blank=True, default='', help_text='AWS IAM Identity Center instance ARN. Leave blank to auto-discover if you have only one instance.', max_length=256, verbose_name='SSO Instance ARN')),
                ('region', models.CharField(blank=True, default='us-east-1', help_text='AWS region where Identity Center is configured', max_length=64, verbose_name='AWS Region')),
                ('role_arn', models.CharField(blank=True, default='', help_text="ARN of an IAM role with SSO Admin permissions. PAM will call STS AssumeRole to get temporary credentials. The role must trust PAM's current identity (instance profile, Roles Anywhere session, or IAM user).", max_length=256, verbose_name='IAM Role ARN to Assume')),
                ('role_session_name', models.CharField(blank=True, default='PAM-Session', help_text='Session name for STS AssumeRole (appears in CloudTrail)', max_length=128, verbose_name='STS Role Session Name')),
                ('external_id', models.CharField(blank=True, default='', help_text='Required if the trust policy has an sts:ExternalId condition', max_length=256, verbose_name='STS External ID (optional)')),
                ('roles_anywhere_profile_arn', models.CharField(blank=True, default='', help_text='ARN of the IAM Roles Anywhere trust profile. Requires a certificate + private key configured via .env: AWS_ROLES_ANYWHERE_CERT_PATH and AWS_ROLES_ANYWHERE_KEY_PATH', max_length=256, verbose_name='Roles Anywhere Profile ARN')),
                ('roles_anywhere_trust_arn', models.CharField(blank=True, default='', help_text='ARN of the IAM Roles Anywhere trust anchor', max_length=256, verbose_name='Roles Anywhere Trust Anchor ARN')),
                ('access_key_id', models.CharField(blank=True, default='', help_text='Long-lived IAM user access key. Only use for development.', max_length=128, verbose_name='IAM Access Key ID (dev only)')),
                ('secret_access_key', models.CharField(blank=True, default='', help_text='Long-lived IAM user secret key. Only use for development.', max_length=256, verbose_name='IAM Secret Access Key (dev only)')),
                ('configured_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Configured by')),
            ],
            options={
                'verbose_name': 'AWS Identity Center Configuration',
                'verbose_name_plural': 'AWS Identity Center Configuration',
            },
        ),
    ]
