# Generated by Django 5.0.14 on 2026-05-09 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REQUEST_CREATED', 'Access Request Created'), ('REQUEST_APPROVED', 'Access Request Approved'), ('REQUEST_DENIED', 'Access Request Denied'), ('PROVISIONING_STARTED', 'Provisioning Started'), ('PROVISIONING_SUCCEEDED', 'Provisioning Succeeded'), ('PROVISIONING_FAILED', 'Provisioning Failed'), ('ACCESS_EXPIRED', 'Access Expired'), ('ACCESS_REVOKED', 'Access Revoked'), ('ROLE_CREATED', 'Privileged Role Created'), ('ROLE_UPDATED', 'Privileged Role Updated'), ('REVIEW_CREATED', 'Access Review Created'), ('REVIEW_COMPLETED', 'Access Review Completed')], max_length=50)),
                ('target_type', models.CharField(blank=True, help_text='Type of object affected (e.g., AccessRequest, PrivilegedRole)', max_length=50)),
                ('target_id', models.CharField(blank=True, help_text='ID of the affected object', max_length=128)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['actor'], name='audit_audit_actor_i_17b775_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx')],
            },
        ),
    ]
