# Generated by Django 5.0.14 on 2026-05-09 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the role', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this role provides')),
                ('provider', models.CharField(choices=[('AWS', 'AWS Identity Center'), ('ENTRA', 'Entra ID PIM')], max_length=10)),
                ('aws_permission_set_arn', models.CharField(blank=True, help_text='AWS SSO Permission Set ARN', max_length=2048)),
                ('aws_account_id', models.CharField(blank=True, help_text='AWS account ID (leave blank for all accounts)', max_length=64)),
                ('aws_account_name', models.CharField(blank=True, help_text='AWS account display name', max_length=255)),
                ('entra_role_id', models.CharField(blank=True, help_text='Entra ID role definition ID', max_length=128)),
                ('entra_role_name', models.CharField(blank=True, help_text='Entra ID role display name', max_length=255)),
                ('max_duration_minutes', models.PositiveIntegerField(default=480, help_text='Maximum allowed duration in minutes')),
                ('requires_approval', models.BooleanField(default=True, help_text='Whether this role requires approval to activate')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is available for requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvers', models.ManyToManyField(blank=True, help_text='Users who can approve requests for this role', related_name='approvable_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'name'],
                'unique_together': {('provider', 'aws_permission_set_arn', 'aws_account_id'), ('provider', 'entra_role_id')},
            },
        ),
    ]
