# Generated by Django 6.0.5 on 2026-05-09 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='privilegedrole',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='privilegedrole',
            constraint=models.UniqueConstraint(condition=models.Q(('provider', 'AWS')), fields=('provider', 'aws_permission_set_arn', 'aws_account_id'), name='unique_aws_role'),
        ),
        migrations.AddConstraint(
            model_name='privilegedrole',
            constraint=models.UniqueConstraint(condition=models.Q(('provider', 'ENTRA')), fields=('provider', 'entra_role_id'), name='unique_entra_role'),
        ),
    ]
