# Generated by Django 5.2.14 on 2026-06-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_privilegedrole_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilegedrole',
            name='abac_enabled',
            field=models.BooleanField(default=False, help_text='Use ABAC via Entra directory attributes instead of direct account assignments'),
        ),
        migrations.AddField(
            model_name='privilegedrole',
            name='entra_attribute_name',
            field=models.CharField(blank=True, default='', help_text='Entra ID extension attribute name (e.g. extension_<appId>_awsAdminAccounts)', max_length=128),
        ),
    ]
