# Generated by Django 5.2.14 on 2026-05-15 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Enable Email Notifications')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=256, verbose_name='SMTP Host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_username', models.CharField(blank=True, default='', max_length=256, verbose_name='SMTP Username')),
                ('smtp_password', models.CharField(blank=True, default='', max_length=512, verbose_name='SMTP Password')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('email_from', models.CharField(blank=True, default='', help_text='Email address used as the sender', max_length=256, verbose_name='From Address')),
                ('slack_enabled', models.BooleanField(default=False, verbose_name='Enable Slack Notifications')),
                ('slack_webhook_url', models.CharField(blank=True, default='', help_text='Incoming webhook URL from Slack Apps', max_length=512, verbose_name='Slack Webhook URL')),
                ('slack_channel', models.CharField(blank=True, default='', help_text='e.g. #pam-notifications', max_length=128, verbose_name='Slack Channel')),
                ('teams_enabled', models.BooleanField(default=False, verbose_name='Enable Teams Notifications')),
                ('teams_webhook_url', models.CharField(blank=True, default='', help_text='Incoming webhook URL from Teams Connector', max_length=512, verbose_name='Teams Webhook URL')),
                ('notify_on_request_created', models.BooleanField(default=True, help_text='Send notification when a new access request is submitted', verbose_name='Request Created')),
                ('notify_on_request_approved', models.BooleanField(default=True, help_text='Send notification when a request is approved', verbose_name='Request Approved')),
                ('notify_on_request_denied', models.BooleanField(default=True, help_text='Send notification when a request is denied', verbose_name='Request Denied')),
                ('notify_on_access_provisioned', models.BooleanField(default=True, help_text='Send notification when access has been provisioned', verbose_name='Access Provisioned')),
                ('notify_on_access_expiring', models.BooleanField(default=False, help_text='Send notification when access is about to expire', verbose_name='Access Expiring Soon')),
                ('configured_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Configured by')),
            ],
            options={
                'verbose_name': 'Notification Configuration',
                'verbose_name_plural': 'Notification Configuration',
            },
        ),
    ]
